apiVersion: extensions/v1beta1
kind: Deployment
metadata:  
  name: broker
spec:  
  replicas: 1
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
       - name: broker
         image: gitlab-registry.cern.ch/rodrigdi/cap-reuse:broker
         ports:
          - containerPort: 5672 
            name: "tcp"
          - containerPort: 15672 
            name: "management"
