apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: step-broker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: step-broker
    spec:
      containers:
       - name: step-broker
         image: gitlab-registry.cern.ch/rodrigdi/cap-reuse:step-broker
         imagePullPolicy: Always
         ports:
          - containerPort: 5000 
            name: "http"
         volumeMounts:
           - name: svaccount
             mountPath: "/var/run/secrets/kubernetes.io/serviceaccount"
      volumes:
       - name: svaccount
         secret:
           secretName: default-token-kul0l
