version: '2'
services:
  broker:
    build: broker
    command: /start.sh test 1234
    ports:
     - "5672:5672"
     - "15672:15672"
  web:
    build: web
    command: python app.py
    depends_on:
     - broker
    links:
     - broker:broker
    ports:
     - "80:5000"
    volumes:
     - ./web:/web
  worker:
    build: worker
    command: celery -A worker worker -l info
    depends_on:
     - rabbit
    links:
     - broker:broker
    volumes:
     - ./worker:/workdir/worker
