apiVersion: v1
kind: ReplicationController
metadata:
  name: atlas-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: atlas-worker
    spec:
      containers:
       - name: celery-worker
         image: diegodelemos/capreuse_worker:latest
         env:
          - name: QUEUE_ENV
            value: atlas-queue
