apiVersion: v1
kind: ReplicationController
metadata:
  name: atlas-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: atlas-worker
    spec:
      containers:
       - name: atlas-celery-worker
         image: diegodelemos/capreuse_worker:kjobs
         env:
          - name: QUEUE_ENV
            value: atlas-queue
         volumeMounts:
          - name: cap-pv
            readOnly: false
            mountPath: "/data"
      volumes:
      - name: cap-pv
        hostPath:
          path: "/data"
