apiVersion: v1
kind: Pod
metadata:
  name: storage-admin
spec:
  containers:
  - name: centos-cephfs
    image: centos:7
    volumeMounts:
    - mountPath: "/mnt/cephfs"
      name: cephfs
    command: ["/bin/sleep", "100000"]
  volumes:
  - name: cephfs
    cephfs:
      monitors:
      - 128.142.36.227:6790
      - 128.142.39.77:6790
      - 128.142.39.144:6790
      path: /k8s
      user: k8s
      secretRef:
        name: ceph-secret
      readOnly: false