apiVersion: v1
kind: PersistentVolume
metadata:
  name: cms-pv
spec:
  accessModes:
   - ReadWriteMany
  capacity:
   storage: 100Mi
  cephfs:
    monitors:
     - 128.142.36.227:6790
     - 128.142.39.77:6790
     - 128.142.39.144:6790
    path: "/k8s/cms"
    user: k8s
    secretRef:
      name: ceph-secret
    readOnly: false
