apiVersion: v1  
kind: ReplicationController  
metadata:  
  name: broker
spec:  
  replicas: 1
  selector:
    app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
       - name: broker
         image: diegodelemos/capreuse_broker:latest
         ports:
          - containerPort: 5672 
            name: "tcp"
          - containerPort: 15672 
            name: "management"
