apiVersion: v1  
kind: ReplicationController  
metadata:  
  name: queue
spec:  
  replicas: 1
  selector:
    app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
       - name: web
         image: diegodelemos/capreuse_web:latest
         ports:
          - containerPort: 5000 
            name: "http"
       - name: worker
         image: diegodelemos/capreuse_worker:latest
       - name: broker
         image: diegodelemos/capreuse_broker:latest
         ports:
          - containerPort: 5672 
            name: "tcp"
          - containerPort: 15672 
            name: "management"

