apiVersion: v1
kind: ReplicationController
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
       - name: flask
         image: diegodelemos/capreuse_web
         ports:
          - containerPort: 5000 
            name: "http"
