apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: "NodePort"
  ports:
  - port: 80
    targetPort: 5000
    name: "http"
    protocol: TCP
    nodePort: 30001 # it is not the safer way, just to test.
  selector:
    app: web
