apiVersion: v1
kind: ReplicationController
metadata:
  name: worker
spec:
  replicas: 2
  selector:
    app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
       - name: worker
         image: diegodelemos/capreuse_worker:latest
