apiVersion: v1
kind: ReplicationController
metadata:
  name: worker
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
       - name: celery-worker
         image: diegodelemos/capreuse_worker:latest
