apiVersion: v1
kind: Service
metadata:
  name: step-broker-service
spec:
  type: "NodePort"
  ports:
  - port: 80
    targetPort: 5000
    name: "http"
    protocol: TCP
  selector:
    app: step-broker
