apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fibo-alice-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fibo-alice-worker
    spec:
      containers:
       - name: fibo-alice-worker
         image: gitlab-registry.cern.ch/rodrigdi/cap-reuse:worker
         imagePullPolicy: Always
         env:
          - name: QUEUE_ENV
            value: fibo-alice-queue
          - name: EXPERIMENT
            value: alice
          - name: SHARED_VOLUME
            value: "/k8s/alice"
         volumeMounts:
          - name: alice-pv
            mountPath: "/data"
      securityContext:
        fsGroup: 0
      volumes:
       - name: alice-pv
         cephfs:
           monitors:
            - 128.142.36.227:6790
            - 128.142.39.77:6790
            - 128.142.39.144:6790
           path: "/k8s/alice"
           user: k8s
           secretRef:
             name: ceph-secret
           readOnly: false
